version: '2'

services:
  web:
    build: .
    image: fridge-flask-app # change as per application
    command: gunicorn --bind 0.0.0.0:5001 -t 0 --workers=15 --timeout 0 app:app # change port number
    volumes:
      - .:/usr/src/app
    expose:
      - 5001 # port for web traffic
      - 1433 # port for mysql
      - 3306 # port for ms sql (prophet)
  nginx:
    build: ./nginx
    image: fridge-nginx # change as per application
    ports:
      - 5001:80 # change port number
    depends_on:
      - web